spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toyPlatform
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
vnpay:
  tmn_code: WF0GYR4R
  hash_secret: KYU6SQGZREITDT5DZP44P2ZE28FJG3J0
  api_url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return_url:  http://localhost:5173/OrderConfirmation
